version: '3.3'

services:
  my_project:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/my_project
    ports:
      - 3000:3000

  my_database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: '${SQL_PASSWORD}'
    ports:
      - 3306:3306
