#220819 수정
version: '3.3'

services:
  my_project:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/MYPROJECT/src #.://MYPROJECT 했을경우 지나치게 느려짐
    ports:
      - 3000:3000

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: '${SQL_PASSWORD}'
    ports:
      - 3306:3306
